/**
 * Site-wide navigation model. The three areas and their order are fixed by
 * CLAUDE.md §2: Home | Work Experience | Academic. These paths are permanent.
 */
export type PageKey = 'home' | 'work' | 'academic';

export interface NavItem {
  key: PageKey;
  label: string;
  /** Unprefixed path; always render through `url()`. */
  path: '/' | '/work' | '/academic';
}

export const NAV: readonly NavItem[] = [
  { key: 'home', label: 'Home', path: '/' },
  { key: 'work', label: 'Work Experience', path: '/work' },
  { key: 'academic', label: 'Academic', path: '/academic' },
] as const;

/** Default Open Graph image per page (1200×630, generated by the og-images skill). */
export const OG_IMAGES: Record<PageKey, string> = {
  home: '/og/home.png',
  work: '/og/work.png',
  academic: '/og/academic.png',
};
