/**
 * Site-wide navigation model. The three areas and their order are fixed by
 * CLAUDE.md §2: Home | Work Experience | Academic. These paths are permanent.
 */
export type PageKey = 'home' | 'work' | 'academic';

export interface NavItem {
  key: PageKey;
  label: string;
  /** One-line description of what the area contains (footer, Home entry cards). UI copy, not CV data. */
  description: string;
  /** Unprefixed path; always render through `url()`. */
  path: '/' | '/work' | '/academic';
}

export const NAV: readonly NavItem[] = [
  {
    key: 'home',
    label: 'Home',
    description: 'Personal introduction, interests and highlights at a glance.',
    path: '/',
  },
  {
    key: 'work',
    label: 'Work Experience',
    description: 'Professional experience, certifications, projects and technical skills.',
    path: '/work',
  },
  {
    key: 'academic',
    label: 'Academic',
    description: 'Degrees, theses, academic projects and simulations.',
    path: '/academic',
  },
] as const;

/** Default Open Graph image per page (1200×630, generated by the og-images skill). */
export const OG_IMAGES: Record<PageKey, string> = {
  home: '/og/home.png',
  work: '/og/work.png',
  academic: '/og/academic.png',
};

/** Section tint for small orientation details (see src/styles/README.md). */
export type Tint = PageKey | 'accent';
